
mounts:
  - source: assets
    target: assets
  - source: node_modules/@qaldek/hugo-enka-cookbook/assets
    target: assets
# layouts
  - source: layouts
    target: layouts
  - source: node_modules/@qaldek/hugo-enka-cookbook/layouts
    target: layouts
  - source: node_modules/@hyas/bootstrap/layouts
    target: layouts

# static
  - source: node_modules/@qaldek/hugo-enka-cookbook/static
    target: static
  - source: static
    target: static

# bootstrap
  - source: node_modules/bootstrap/scss
    target: assets/scss/bootstrap
  - source: node_modules/bootstrap/dist/js/bootstrap.bundle.js
    target: assets/js/bootstrap.js


# flatpickr
  - source: node_modules/flatpickr/dist/
    target: assets/flatpickr

# vuejs2
  - source: node_modules/vue/dist/vue.min.js
    target: assets/js/vendor/vue.min.js  
  - source: node_modules/vue/dist/vue.js
    target: assets/js/vendor/vue.js

# vuetify
  - source: node_modules/vuetify/dist/vuetify.js
    target: assets/js/vendor/vuetify.js
  - source: node_modules/vuetify/dist/vuetify.min.css
    target: assets/css/vendor/vuetify.min.css

  