# Import assets from hugo-enka-cookbook theme (bootstrap, vue, vuetify, flatpickr, ...js and css)
imports: 
  - path: "github.com/encas-parka/hugo-enka-cookbook"
    mounts:
      - source: assets
        target: assets
      - source: layouts
        target: layouts
      - source: static
        target: static



mounts: 
  - source: assets
    target: assets
  # layouts
  - source: layouts
    target: layouts
  # static
  - source: static
    target: static