imports: 
  - path: github.com/encas-parka/enka-cookbook-site
  

mounts: 
  - source: layouts
    target: layouts
  - source: static
    target: static
  - source: assets
    target: assets
  - source: data
    target: data

