imports: 
  - path: github.com/encas-parka/hugo-enka-cookbook
    mounts: 
      - source: layouts
        target: layouts
      - source: static
        target: static
      - source: assets
        target: assets

mounts: 
  - source: layouts
    target: layouts
  - source: static
    target: static
  - source: assets
    target: assets
  - source: data
    target: data

