imports:
  - path: github.com/encas-parka/enka-cookbook
    mounts: 
      - source: assets
        target: assets 
      - source: layouts 
        target: layouts 
      - source: static 
        target: static  
      - source: node_modules/@hyas/core/assets
        target: assets
      - source: node_modules/@hyas/core/layouts
        target: layouts
      - source: node_modules/gethyas/assets
        target: assets
      - source: node_modules/gethyas/static
        target: static
      - source: node_modules/bootstrap/scss
        target: assets/scss/bootstrap
      - source: node_modules/@hyas/bootstrap/layouts
        target: layouts



# mounts:
  
#   - source: assets
#     target: assets
#   - source: layouts
#     target: layouts
#   - source: static
#     target: static
 