 
name: Netlify Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DEPLOY_MAIN }}
