on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Extraire les fichiers Markdown modifiés
        id: changed-files
        if: contains(github.event.head_commit.message, ' Recettes ') || contains(github.event.head_commit.message, ' Evenements ')
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "name=files::$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Vérifier draft
        id: check-draft
        if: steps.changed-files.outputs.files
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            if [[ $file == content/recettes/* || $file == content/evenements/* ]]; then
              yaml_header=$(sed -n '/^---/,/^---/p' $file)
              if echo "$yaml_header" | grep -q 'draft: true'; then
                echo "Le fichier $file contient draft: true, déploiement ignoré"
                exit 1
              fi
            fi
          done

      - name: Construire et déployer Hugo
        if: steps.check-draft.outcome == 'success'
        run: curl -X POST ${{ secrets.CF_HOOK_DEPLOY }}