on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vérifier le message de commit
        id: check-commit-msg
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if echo "$COMMIT_MSG" | grep -qE '(recettes|evenements)'; then
            echo "check=true" >> $GITHUB_OUTPUT
          else
            echo "check=false" >> $GITHUB_OUTPUT
          fi

      - name: Extraire les fichiers Markdown modifiés
        id: changed-files
        if: steps.check-commit-msg.outputs.check == 'true'
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "name=files::$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Vérifier draft
        id: check-draft
        if: steps.changed-files.outputs.files
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            if [[ $file == content/recettes/* || $file == content/evenements/* ]]; then
              yaml_header=$(sed -n '/^---/,/^---/p' $file)
              if echo "$yaml_header" | grep -q 'draft: true'; then
                echo "Le fichier $file contient draft: true, déploiement ignoré"
                exit 1
              fi
            fi
          done

      - name: Construire et déployer Hugo
        if: steps.check-draft.outcome == 'success'
        run: curl -X POST ${{ secrets.CF_HOOK_DEPLOY }}