name: Markdown Check and Deploy

on:
  push:
    paths:
      - '**.md'

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  
    - name: Check Markdown files
      run: |
        npm install -g front-matter-cli
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '.md$'); do
          if ! fm --yaml $file | grep -q 'draft: false'; then
            echo "Draft is not false in $file. Aborting."
            exit 1
          fi
          if ! fm --yaml $file | grep -q 'uuid:'; then
            echo "Adding uuid to $file."
            fm --yaml --append "uuid: $(date +%s)" $file
          fi
        done

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add missing uuid to markdown files" || echo "No changes to commit"
        git push

    - name: Deploy to Cloudflare
      run: |
        # Add your Cloudflare deployment command here


    - name: Deploy to Cloudflare Pages
      run: curl -X POST ${{ secrets.CF_HOOK_DEPLOY }}

    - name: Deploy to Netlify
      if: contains(github.event.head_commit.message, 'netlify-deploy')
      run: curl -X POST ${{ secrets.NETLIFY_DEPLOY_MAIN }}
