name: Check Markdown Files and Deploy

on:
  push:
    branches:
      - main

jobs:

  check-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'test-deploy') "
    steps:
    - uses: actions/checkout@v3

    - name: Check and update markdown files
      id: check-files
      run: |
       - name: Check and update markdown files
  id: check-files
  run: |
    draft_found='false'
    for file in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.md$'); do
      has_uuid=$(awk '/^uuid:/ {print $2; exit}' $file)
      if [ -z "$has_uuid" ]; then
        timestamp=$(date +%s%3N)
        uuid="$timestamp"
        awk '/^---/ {print $0 RS "uuid: " uuid RS; next} 1' $file > tmp && mv tmp $file
      fi
      draft=$(awk '/^draft:/ {print $2; exit}' $file)
      if [ "$draft" == "false" ]; then
        draft_found='true'
        break
      fi
    done
    echo "draft_found=$draft_found" >> $GITHUB_OUTPUT

    - name: Deploy to Cloudflare Pages
      if: steps.check-files.outputs.draft_found == 'true'
      run: curl -X POST ${{ secrets.CF_HOOK_DEPLOY }}

    - name: Deploy to Netlify
      if: contains(github.event.head_commit.message, 'netlify-deploy')
      run: curl -X POST ${{ secrets.NETLIFY_DEPLOY_MAIN }}
