name: Check Markdown Files and Deploy

on:
  push:
    branches:
      - main

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'test-deploy')"

    steps:
    - uses: actions/checkout@v4

    - name: Check and update markdown files
      id: check-files
      run: |
        draft_found=false
        for file in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.md$'); do
          has_uuid=$(awk '/^uuid:/ {print $2; exit}' $file)
          if [ -z "$has_uuid" ]; then
            title=$(awk '/^title:/ {print $2; exit}' $file)
            slug=$(echo $title | sed 's/ /-/g' | awk '{print tolower($0)}')
            timestamp=$(date +%s%3N)
            uuid="$timestamp-$slug"
            awk -v uuid="$uuid" '/^---/ {print; print "uuid: " uuid; next}1' $file > tmp && mv tmp $file
          fi
          draft=$(awk '/^draft:/ {print $2; exit}' $file)
          if [ "$draft" == "false" ]; then
            draft_found=true
          fi
        done
        echo "draft_found=$draft_found" >> $GITHUB_ENV

    - name: Deploy to Cloudflare Pages
      if: env.draft_found == 'true'
      run: curl -X POST ${{ secrets.CF_HOOK_DEPLOY }}

    - name: Deploy to Netlify
      if: contains(github.event.head_commit.message, 'netlify-deploy')
      run: curl -X POST ${{ secrets.NETLIFY_DEPLOY_MAIN }}
